#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// OpenCometBench/generate-pages.mjs — SIH v1.13 (REAL BROWSER benchmark pages)
//
// Emits OpenCometBench/pages/*.html — self-contained synthetic pages with
// EMBEDDED GROUND TRUTH (window.__SIH_GT__):
//   pageType          expected classification (matches page-classifier.js vocabulary)
//   sensitiveElements password/PII fields with selectors  → redaction GT
//   actionControls    elements the agent must be able to act on
//   importantElements page landmarks the visual context should surface
//
// The GT boxes are NOT baked as pixels — the harness measures them live via
// getBoundingClientRect at whatever DPR / zoom / scroll the run uses, so the
// benchmark stays honest across the whole matrix.
//
//   node OpenCometBench/generate-pages.mjs
// ─────────────────────────────────────────────────────────────────────────────
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = join(dirname(fileURLToPath(import.meta.url)), 'pages');
mkdirSync(OUT, { recursive: true });

const BASE_CSS = `
  * { box-sizing: border-box; margin: 0; }
  body { font: 14px/1.5 system-ui, sans-serif; color: #1a2233; background: #f6f7fb; }
  header { background: #16213e; color: #fff; padding: 14px 24px; font-size: 18px; font-weight: 600; }
  main { max-width: 980px; margin: 24px auto; padding: 0 16px; }
  .card { background: #fff; border: 1px solid #dfe4ef; border-radius: 10px; padding: 20px; margin-bottom: 18px; }
  label { display: block; margin: 10px 0 4px; font-weight: 600; font-size: 13px; }
  input, select, textarea { width: 100%; padding: 8px 10px; border: 1px solid #c3cbdd; border-radius: 6px; font: inherit; }
  button, .btn { background: #1d6ef5; border: 0; color: #fff; padding: 9px 18px; border-radius: 8px; font-weight: 600; cursor: pointer; margin-top: 12px; }
  .row { display: flex; gap: 12px; } .row > * { flex: 1; }
  .muted { color: #667; font-size: 12px; }
  a { color: #1d6ef5; }
  nav a { margin-right: 14px; }
  .dialog { position: fixed; inset: 0; background: rgba(10,14,30,.45); display: none; align-items: center; justify-content: center; z-index: 50; }
  .dialog.open { display: flex; }
  .dialog .box { background: #fff; border-radius: 12px; padding: 24px; width: 420px; }
  table { border-collapse: collapse; width: 100%; } td, th { border: 1px solid #dfe4ef; padding: 6px 10px; text-align: left; font-size: 13px; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
  .stat { background: #eef3ff; border-radius: 8px; padding: 14px; font-size: 20px; font-weight: 700; }
`;

const GT_SCRIPT = (gt) => `<script id="sih-gt">
window.__SIH_GT__ = ${JSON.stringify(gt, null, 2)};
</script>`;

function page(name, title, gt, bodyJs) {
  return `<!DOCTYPE html>
<!-- Synthetic SIH benchmark page — generated by OpenCometBench/generate-pages.mjs.
     ALL data is fake. Ground truth is embedded as window.__SIH_GT__. -->
<html lang="en">
<head>
<meta charset="utf-8"><title>${title}</title>
<style>${BASE_CSS}</style>
${GT_SCRIPT(gt)}
</head>
<body>
<header>${title}</header>
<main>
${bodyJs}
</main>
</body>
</html>`;
}

const pages = {};

// ── 1. login ────────────────────────────────────────────────────────────────
pages['login'] = page('login', 'Sign in — Example Accounts', {
  pageType: 'login',
  sensitiveElements: [
    { id: 'pw', type: 'password', selector: '#pw', desc: 'password field' },
    { id: 'em', type: 'email_value', selector: '#em', desc: 'email field (value typed by E2E)' },
  ],
  actionControls: [
    { id: 'submit', kind: 'submit', selector: '#submit', desc: 'Sign in button' },
    { id: 'forgot', kind: 'link', selector: '#forgot', desc: 'Forgot password link' },
  ],
  importantElements: ['form', 'password_field', 'email_field', 'button'],
}, `
<div class="card">
  <form onsubmit="return false">
    <label for="em">Email</label><input id="em" type="email" placeholder="you@example.com">
    <label for="pw">Password</label><input id="pw" type="password" placeholder="Password">
    <button id="submit" type="submit">Sign in</button>
    <p class="muted"><a href="#" id="forgot">Forgot password?</a> · <a href="#">Create account</a></p>
  </form>
</div>`);

// ── 2. signup ───────────────────────────────────────────────────────────────
pages['signup'] = page('signup', 'Create your account — Example', {
  pageType: 'signup',
  sensitiveElements: [
    { id: 'pw1', type: 'password', selector: '#pw1', desc: 'new password' },
    { id: 'pw2', type: 'password', selector: '#pw2', desc: 'confirm password' },
  ],
  actionControls: [{ id: 'register', kind: 'submit', selector: '#register', desc: 'Create account button' }],
  importantElements: ['form', 'password_field', 'email_field', 'button'],
}, `
<div class="card">
  <form onsubmit="return false">
    <label>Full name</label><input id="nm" placeholder="Full name">
    <label>Email</label><input id="em2" type="email" placeholder="you@example.com">
    <div class="row">
      <div><label>Password</label><input id="pw1" type="password"></div>
      <div><label>Confirm</label><input id="pw2" type="password"></div>
    </div>
    <button id="register" type="submit">Create account</button>
  </form>
</div>`);

// ── 3. checkout ─────────────────────────────────────────────────────────────
pages['checkout'] = page('checkout', 'Checkout — Example Store', {
  pageType: 'checkout',
  sensitiveElements: [
    { id: 'addr', type: 'sensitive_input', selector: '#addr', desc: 'shipping address' },
    { id: 'phone', type: 'sensitive_input', selector: '#phone', desc: 'phone' },
  ],
  actionControls: [{ id: 'place-order', kind: 'submit', selector: '#place-order', desc: 'Place your order' }],
  importantElements: ['form', 'price_display', 'order_summary', 'button'],
}, `
<div class="card"><h2>Order summary</h2>
<table><tr><th>Item</th><th>Price</th></tr>
<tr><td>Wireless mouse</td><td>₹1,299</td></tr><tr><td>USB-C hub</td><td>₹2,199</td></tr>
<tr><th>Total</th><th id="total">₹3,498</th></tr></table></div>
<div class="card"><form onsubmit="return false">
  <label>Delivery address</label><textarea id="addr" rows="2"></textarea>
  <label>Phone</label><input id="phone" type="tel">
  <button id="place-order" type="submit">Place your order</button>
</form></div>`);

// ── 4. payment ──────────────────────────────────────────────────────────────
pages['payment'] = page('payment', 'Payment — Example Pay', {
  pageType: 'payment',
  sensitiveElements: [
    { id: 'cc', type: 'sensitive_input', selector: '#cc', desc: 'card number (autocomplete cc-number)' },
    { id: 'cvv', type: 'sensitive_input', selector: '#cvv', desc: 'CVV' },
    { id: 'cardname', type: 'sensitive_input', selector: '#cardname', desc: 'card holder' },
  ],
  actionControls: [{ id: 'pay', kind: 'submit', selector: '#pay', desc: 'Pay now' }],
  importantElements: ['form', 'payment_form', 'price_display', 'button'],
}, `
<div class="card"><form onsubmit="return false">
  <label>Amount</label><div class="stat">₹3,498</div>
  <label>Card number</label><input id="cc" autocomplete="cc-number" inputmode="numeric" placeholder="•••• •••• •••• ••••">
  <div class="row">
    <div><label>Card holder</label><input id="cardname" autocomplete="cc-name"></div>
    <div><label>Expiry</label><input id="exp" autocomplete="cc-exp" placeholder="MM/YY"></div>
    <div><label>CVV</label><input id="cvv" autocomplete="cc-csc" inputmode="numeric"></div>
  </div>
  <button id="pay" type="submit">Pay now</button>
  <p class="muted">UPI / net banking also accepted at checkout.</p>
</form></div>`);

// ── 5. banking ──────────────────────────────────────────────────────────────
pages['banking'] = page('banking', 'My Accounts — Example Bank Net Banking', {
  pageType: 'banking',
  sensitiveElements: [
    { id: 'acct', type: 'sensitive_input', selector: '#acct', desc: 'account number field' },
  ],
  actionControls: [
    { id: 'transfer', kind: 'button', selector: '#transfer', desc: 'Transfer funds' },
    { id: 'statement', kind: 'button', selector: '#statement', desc: 'Download statement' },
  ],
  importantElements: ['dashboard_census', 'button'],
}, `
<nav style="padding:0 24px"><a href="#">Overview</a><a href="#">Beneficiary list</a><a href="#">IFSC lookup</a><a href="#">Statements</a></nav>
<div class="card"><div class="grid">
  <div class="stat">₹ 84,210.55<br><span class="muted">Savings ••4821</span></div>
  <div class="stat">₹ 12,000.00<br><span class="muted">FD ••9903</span></div>
  <div class="stat">₹ 2,140.00<br><span class="muted">Credit ••1177</span></div>
</div>
<label>Account number (for transfer)</label><input id="acct">
<button id="transfer">Transfer funds</button> <button id="statement" class="btn" style="background:#2a3550">Download statement</button>
</div>`);

// ── 6. dashboard ────────────────────────────────────────────────────────────
pages['dashboard'] = page('dashboard', 'Analytics Dashboard — Example HQ', {
  pageType: 'dashboard',
  sensitiveElements: [],
  actionControls: [
    { id: 'range', kind: 'select', selector: '#range', desc: 'date range selector' },
  ],
  importantElements: ['dashboard_census', 'stat_tile'],
}, `
<div class="card"><div class="row">
  <div><label>Range</label><select id="range"><option>Last 7 days</option><option>Last 30 days</option></select></div>
</div></div>
<div class="card"><div class="grid">
  <div class="stat">12,482<br><span class="muted">Visitors</span></div>
  <div class="stat">3.42%<br><span class="muted">Conversion</span></div>
  <div class="stat">₹ 4.2L<br><span class="muted">Revenue</span></div>
</div>
<canvas id="chart" width="900" height="180" style="margin-top:12px;border:1px solid #dfe4ef;border-radius:8px"></canvas>
<script>
  const c = document.getElementById('chart').getContext('2d');
  c.strokeStyle = '#1d6ef5'; c.lineWidth = 2; c.beginPath();
  for (let x = 0; x <= 900; x += 10) c.lineTo(x, 90 + Math.sin(x / 60) * 45);
  c.stroke();
</${'script'}>
</div>`);

// ── 7. email ────────────────────────────────────────────────────────────────
pages['email'] = page('email', 'Inbox — Example Mail', {
  pageType: 'email',
  sensitiveElements: [
    { id: 'compose-to', type: 'sensitive_input', selector: '#compose-to', desc: 'compose recipients' },
  ],
  actionControls: [
    { id: 'compose', kind: 'button', selector: '#compose', desc: 'Compose button' },
    { id: 'send', kind: 'button', selector: '#send', desc: 'Send button' },
  ],
  importantElements: ['compose_editor', 'email_census', 'button'],
}, `
<div class="card"><button id="compose">✏️ Compose</button></div>
<div class="card" id="compose-card" style="display:none">
  <label>To</label><input id="compose-to" placeholder="recipient@example.com">
  <label>Subject</label><input id="compose-subject">
  <textarea rows="4" placeholder="Message"></textarea>
  <button id="send">Send</button>
</div>
<div class="card"><table>
  <tr><td><b>Quarterly report</b></td><td>finance@example corp</td><td>09:41</td></tr>
  <tr><td><b>Welcome aboard</b></td><td>people team</td><td>Yesterday</td></tr>
  <tr><td><b>Your statement is ready</b></td><td>no-reply@example bank</td><td>Mon</td></tr>
</table></div>
<script>
  document.getElementById('compose').addEventListener('click', () => {
    document.getElementById('compose-card').style.display = 'block';
  });
</${'script'}>`);

// ── 8. article ──────────────────────────────────────────────────────────────
pages['article'] = page('article', 'On-device AI — Example Blog', {
  pageType: 'article',
  sensitiveElements: [],
  actionControls: [{ id: 'share', kind: 'button', selector: '#share', desc: 'Share button' }],
  importantElements: ['article_census'],
}, `
<div class="card">
  <h1>On-device AI: why the next browser agent runs locally</h1>
  <p class="muted">Posted on March 2025 by the Example team · 8 minutes read</p>
  <p style="margin-top:12px">Large vision models no longer need a datacenter to be useful. This article walks
  through the architecture of a fully local perception stack: a quantized vision transformer classifies the
  screen, a lightweight detector finds faces, and a deterministic PII engine masks text — all before any
  network call happens.</p>
  <p style="margin-top:12px">The second section covers latency budgets. A sanitized 1280-pixel frame carries
  roughly a quarter of the vision tokens of a full-resolution capture, which is why on-device redaction is
  also a speed feature, not only a privacy feature.</p>
  <p style="margin-top:12px">Finally we look at failure policy: when a detector is unavailable the system must
  fail closed, never silently shipping pixels the user believed were protected.</p>
  <button id="share">Share</button> <span class="muted">Comments (12)</span>
</div>`);

// ── 9. media ────────────────────────────────────────────────────────────────
pages['media'] = page('media', 'Now Playing — Example Music', {
  pageType: 'media',
  sensitiveElements: [],
  actionControls: [
    { id: 'play', kind: 'button', selector: '#play', desc: 'Play/pause control' },
  ],
  importantElements: ['media_player', 'video_census'],
}, `
<div class="card" style="text-align:center">
  <video id="player" width="640" height="360" style="background:#111;border-radius:8px" muted playsinline
         onended="this.currentTime=0"></video>
  <div style="margin-top:10px">
    <button id="play">▶ Play</button>
    <span style="margin-left:10px">Synthetic media — generated locally, no assets fetched.</span>
  </div>
</div>
<div class="card"><b>Up next</b>: Synth Wave 01 · Synth Wave 02 · Ambient Loop 03</div>
<script>
  const v = document.getElementById('player');
  const btn = document.getElementById('play');
  // Draw an animated pattern so the video element carries real, changing pixels.
  const c = document.createElement('canvas'); c.width = 640; c.height = 360;
  const ctx = c.getContext('2d'); let t = 0;
  function draw() {
    ctx.fillStyle = '#101425'; ctx.fillRect(0, 0, 640, 360);
    for (let i = 0; i < 24; i++) {
      ctx.fillStyle = 'hsl(' + ((i * 14 + t) % 360) + ',70%,55%)';
      ctx.fillRect(20 + i * 25, 180 + Math.sin(t / 20 + i) * 90, 16, 60);
    }
    t++; requestAnimationFrame(draw);
  }
  draw();
  btn.addEventListener('click', () => {
    if (v.paused) { try { v.srcObject = c.captureStream(24); } catch (e) {} v.play(); btn.textContent = '⏸ Pause'; }
    else { v.pause(); btn.textContent = '▶ Play'; }
  });
</${'script'}>`);

// ── 10. government form ─────────────────────────────────────────────────────
pages['gov-form'] = page('gov-form', 'Apply Online — Certificate Scheme (Government Portal)', {
  pageType: 'government',
  sensitiveElements: [
    { id: 'g-aadhaar', type: 'sensitive_input', selector: '#g-aadhaar', desc: 'aadhaar field' },
    { id: 'g-pan', type: 'sensitive_input', selector: '#g-pan', desc: 'PAN field' },
    { id: 'g-doc', type: 'file_input', selector: '#g-doc', desc: 'document upload' },
  ],
  actionControls: [{ id: 'g-submit', kind: 'submit', selector: '#g-submit', desc: 'Submit application' }],
  importantElements: ['form', 'file_upload', 'government_census'],
}, `
<div class="card">
  <p class="muted">Government of Example — scheme application portal. Apply online with your documents.</p>
  <form onsubmit="return false">
    <label>Applicant name</label><input id="g-name">
    <div class="row">
      <div><label>Aadhaar number</label><input id="g-aadhaar" name="aadhaar" placeholder="XXXX XXXX XXXX"></div>
      <div><label>PAN</label><input id="g-pan" name="pan" placeholder="ABCDE1234F"></div>
    </div>
    <div class="row">
      <div><label>Date of birth</label><input id="g-dob" type="date"></div>
      <div><label>Upload document</label><input id="g-doc" type="file"></div>
    </div>
    <button id="g-submit" type="submit">Submit application</button>
  </form>
</div>`);

// ── 11. canvas-heavy application ────────────────────────────────────────────
pages['canvas-app'] = page('canvas-app', 'Design Editor — Example Canvas', {
  pageType: 'form',
  sensitiveElements: [],
  actionControls: [
    { id: 'tool-brush', kind: 'button', selector: '#tool-brush', desc: 'brush tool' },
    { id: 'tool-shape', kind: 'button', selector: '#tool-shape', desc: 'shape tool' },
    { id: 'export', kind: 'button', selector: '#export', desc: 'export button' },
  ],
  importantElements: ['canvas_app', 'thin_dom'],
}, `
<div class="card" style="display:flex;gap:10px">
  <div style="width:120px">
    <button id="tool-brush" style="width:100%">Brush</button>
    <button id="tool-shape" style="width:100%;background:#2a3550">Shape</button>
    <button id="export" style="width:100%;background:#2a3550">Export</button>
  </div>
  <canvas id="stage" width="720" height="420" style="border:1px solid #c3cbdd;border-radius:6px;flex:1"></canvas>
</div>
<script>
  const s = document.getElementById('stage').getContext('2d');
  s.fillStyle = '#fff'; s.fillRect(0, 0, 720, 420);
  s.strokeStyle = '#1d6ef5'; s.lineWidth = 3;
  s.strokeRect(60, 60, 220, 140); s.beginPath(); s.arc(520, 220, 90, 0, Math.PI * 2); s.stroke();
  s.beginPath(); s.moveTo(80, 340); s.lineTo(300, 380); s.lineTo(660, 320); s.stroke();
</${'script'}>`);

// ── 12. mixed UI ────────────────────────────────────────────────────────────
pages['mixed-ui'] = page('mixed-ui', 'Example Portal — Home', {
  pageType: 'unknown',
  sensitiveElements: [
    { id: 'm-search', type: 'sensitive_input', selector: '#m-search', desc: 'search box' },
  ],
  actionControls: [
    { id: 'm-search-btn', kind: 'button', selector: '#m-search-btn', desc: 'search button' },
    { id: 'm-link-docs', kind: 'link', selector: '#m-link-docs', desc: 'docs link' },
  ],
  importantElements: ['mixed_census'],
}, `
<nav class="card"><a href="#" id="m-link-docs">Docs</a><a href="#">Pricing</a><a href="#">Blog</a><a href="#">Account</a></nav>
<div class="card"><div class="row">
  <input id="m-search" placeholder="Search the portal…">
  <button id="m-search-btn" style="margin:0">Search</button>
</div></div>
<div class="card"><div class="grid">
  <div><h3>Projects</h3><p class="muted">3 active</p></div>
  <div><h3>Invoices</h3><p class="muted">1 due</p></div>
  <div><h3>Team</h3><p class="muted">8 members</p></div>
</div></div>
<div class="card"><h3>Recommended</h3><a href="#">Getting started guide</a> · <a href="#">API reference</a></div>`);

// ── redaction-lab: the DPR/zoom/scroll/dialog matrix target ─────────────────
pages['redaction-lab'] = page('redaction-lab', 'Redaction Lab — Multi-region Sensitivity', {
  pageType: 'form',
  sensitiveElements: [
    { id: 'rl-pass', type: 'password', selector: '#rl-pass', desc: 'password' },
    { id: 'rl-card', type: 'sensitive_input', selector: '#rl-card', desc: 'card number' },
    { id: 'rl-email', type: 'sensitive_input', selector: '#rl-email', desc: 'email' },
    { id: 'rl-phone', type: 'sensitive_input', selector: '#rl-phone', desc: 'phone' },
    { id: 'rl-addr', type: 'sensitive_input', selector: '#rl-addr', desc: 'address' },
    { id: 'dl-pass', type: 'password', selector: '#dl-pass', desc: 'dialog password', dialog: true },
  ],
  actionControls: [
    { id: 'rl-open-dialog', kind: 'button', selector: '#rl-open-dialog', desc: 'open sensitive dialog' },
    { id: 'rl-save', kind: 'submit', selector: '#rl-save', desc: 'save' },
  ],
  importantElements: ['form'],
}, `
<div class="card"><form onsubmit="return false">
  <label>Username</label><input id="rl-user" value="demo_user">
  <label>Password</label><input id="rl-pass" type="password" value="hunter2">
  <label>Card number</label><input id="rl-card" autocomplete="cc-number" value="4532 0151 1283 0366">
  <label>Email</label><input id="rl-email" type="email" value="jane.doe@example.com">
  <label>Phone</label><input id="rl-phone" type="tel" value="+91 98765 43210">
  <label>Address</label><textarea id="rl-addr" rows="2">221B Baker Street, London NW1 6XE</textarea>
  <button id="rl-open-dialog" type="button">Open secure dialog</button>
  <button id="rl-save" type="submit">Save profile</button>
</form></div>
<div class="card" style="height:600px"><h3>Spacer</h3><p class="muted">Gives the page real scroll depth.</p></div>
<div class="dialog" id="rl-dialog"><div class="box">
  <h3>Secure — re-enter password</h3>
  <label>Password</label><input id="dl-pass" type="password" value="hunter2">
  <button onclick="document.getElementById('rl-dialog').classList.remove('open')">Close</button>
</div></div>
<script>
  document.getElementById('rl-open-dialog').addEventListener('click', () =>
    document.getElementById('rl-dialog').classList.add('open'));
</${'script'}>`);

// ── 11b. PIXEL-ONLY CONTROLS (v1.14 Task: visual-element GT by source) ──────
// These two pages carry ACTION CONTROLS that exist ONLY as painted pixels:
// the DOM census sees canvases/SVG shapes but ZERO button/submit semantics.
// They anchor the harness's element-source split: DOM-semantic controls must
// be found by the classifier; pixel-only controls are, BY DESIGN, invisible
// to DOM-derived elements — the honest measured result documents exactly
// which surfaces need the visualDetector/OCR paths.
pages['canvas-controls'] = page('canvas-controls', 'Canvas Paint — Example Studio', {
  pageType: 'form',
  sensitiveElements: [],
  actionControls: [
    { id: 'px-undo', kind: 'button', via: 'pixels-only', selector: null, desc: 'Undo control painted on canvas' },
    { id: 'px-clear', kind: 'button', via: 'pixels-only', selector: null, desc: 'Clear control painted on canvas' },
    { id: 'px-save', kind: 'submit', via: 'pixels-only', selector: null, desc: 'Save control painted on canvas' },
  ],
  importantElements: ['canvas_app', 'thin_dom'],
}, `
<div class="card">
  <p class="muted">All controls below are painted on the canvas — no DOM buttons exist.</p>
  <canvas id="pxboard" width="760" height="300" style="border:1px solid #c3cbdd;border-radius:8px;background:#fff"></canvas>
</div>
<script>
  (function () {
    const c = document.getElementById('pxboard'), x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, c.width, c.height);
    const drawBtn = (label, bx, primary) => {
      x.fillStyle = primary ? '#1d6ef5' : '#eef1f8'; x.strokeStyle = '#c3cbdd';
      x.beginPath(); x.roundRect(bx, 30, 130, 44, 8); x.fill(); x.stroke();
      x.fillStyle = primary ? '#ffffff' : '#1a2233'; x.font = '600 16px system-ui';
      x.fillText(label, bx + 18, 58);
    };
    drawBtn('Undo', 30, false); drawBtn('Clear', 180, false); drawBtn('Save', 330, true);
    x.fillStyle = '#5a6478'; x.font = '14px system-ui';
    x.fillText('Canvas paint surface — 0 × 0 strokes', 30, 120);
  })();
</script>`);

pages['svg-controls'] = page('svg-controls', 'SVG Flow Designer — Example', {
  pageType: 'form',
  sensitiveElements: [],
  actionControls: [
    { id: 'svg-zoom-in', kind: 'button', via: 'pixels-only', selector: null, desc: 'zoom-in SVG shape control (no button role)' },
    { id: 'svg-zoom-out', kind: 'button', via: 'pixels-only', selector: null, desc: 'zoom-out SVG shape control (no button role)' },
    { id: 'svg-run', kind: 'submit', via: 'pixels-only', selector: null, desc: 'run SVG shape control (no button role)' },
  ],
  importantElements: ['canvas_app', 'thin_dom'],
}, `
<div class="card">
  <p class="muted">Controls are bare SVG shapes with click handlers — no &lt;button&gt;, no role, no aria-label.</p>
  <svg id="svgboard" width="760" height="220" style="background:#fff;border:1px solid #c3cbdd;border-radius:8px">
    <rect id="svg-zoom-in-shape" x="30" y="30" width="120" height="46" rx="8" fill="#eef1f8" stroke="#c3cbdd"></rect>
    <text x="58" y="59" font-family="system-ui" font-size="16" fill="#1a2233">＋ Zoom</text>
    <rect id="svg-zoom-out-shape" x="170" y="30" width="120" height="46" rx="8" fill="#eef1f8" stroke="#c3cbdd"></rect>
    <text x="196" y="59" font-family="system-ui" font-size="16" fill="#1a2233">－ Zoom</text>
    <rect id="svg-run-shape" x="310" y="30" width="120" height="46" rx="8" fill="#1d6ef5"></rect>
    <text x="346" y="59" font-family="system-ui" font-size="16" fill="#ffffff">▶ Run</text>
  </svg>
</div>
<script>
  document.getElementById('svg-zoom-in-shape').addEventListener('click', () => {});
  document.getElementById('svg-zoom-out-shape').addEventListener('click', () => {});
  document.getElementById('svg-run-shape').addEventListener('click', () => {});
</script>`);

// ── pii-visual: PII that ONLY exists in pixels (canvas / SVG img / PDF-like) ─
// v1.13: the "PDF-like" page is now rendered ONTO A CANVAS — earlier drafts
// used absolutely-positioned DIVs whose text was still DOM-visible (the
// benchmark honestly flagged that via textPii>0). All three surfaces are now
// true pixel-only. The page MEASURES its own painted text lines and exposes
// the line boxes in window.__SIH_GT__.ocrPiiBoxes (viewport-absolute CSS px).
pages['pii-visual'] = page('pii-visual', 'Visual-only PII Lab (canvas / image / PDF-like)', {
  pageType: 'form',
  domMustNotContain: ['jane.doe@example.com', '+91 98765 43210', '2345 1234 5909', 'sk-proj-abcdefghij1234567890'],
  visualPiiElements: [
    { id: 'v-canvas', kind: 'canvas', selector: '#v-canvas', desc: 'canvas-painted PII text' },
    { id: 'v-img', kind: 'img', selector: '#v-img', desc: 'SVG-data-URL image with PII text' },
    { id: 'v-pdf', kind: 'canvas', selector: '#v-pdf', desc: 'canvas-rendered PDF-like statement page' },
  ],
  sensitiveElements: [],
  actionControls: [],
  importantElements: ['visual_pii'],
  ocrTargets: [
    { id: 'v-canvas', text: 'Contact: jane.doe@example.com', types: ['email'] },
    { id: 'v-img', text: 'Call +91 98765 43210', types: ['phone'] },
    { id: 'v-pdf', text: 'Aadhaar: 2345 1234 5909', types: ['aadhaar'] },
    { id: 'v-pdf', text: 'API key: sk-proj-abcdefghij1234567890', types: ['api_key'] },
  ],
  // ocrPiiBoxes are filled in at paint time by the page script below.
  ocrPiiBoxes: [],
}, `
<div class="card">
  <p class="muted">Every value below exists ONLY as pixels (canvas paint, SVG data-URL image, canvas-rendered
  statement). The DOM text contains none of it — DOM-only PII scanning cannot see any of it; only the
  OCR / visual pipeline can. The page measures its own painted PII-substring boxes into window.__SIH_GT__.ocrPiiBoxes.</p>
  <canvas id="v-canvas" width="640" height="90" style="border:1px solid #dfe4ef;border-radius:8px;margin:8px 0"></canvas>
  <div><img id="v-img" width="520" height="70" alt="contact card" style="border:1px solid #dfe4ef;border-radius:8px;margin:8px 0"></div>
  <canvas id="v-pdf" width="640" height="150" style="border:1px solid #dfe4ef;box-shadow:0 1px 6px rgba(0,0,0,.15);margin:8px 0"></canvas>
</div>
<script>
  function paintLines(ctx, lines) {
    ctx.fillStyle = '#ffffff'; ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
    ctx.fillStyle = '#111827'; ctx.font = '20px system-ui, sans-serif'; ctx.textBaseline = 'top';
    lines.forEach((t, i) => ctx.fillText(t, 24, 14 + i * 30));
  }
  // Self-measured GROUND TRUTH: the exact PII-substring pixel box for each
  // painted value (prefix-measured with the same font the surface used).
  // textBaseline='top' means the paint y IS the glyph top.
  function measurePii(canvasEl, fullText, piiText, ty, fontSize) {
    const ctx = canvasEl.getContext('2d');
    ctx.font = '20px system-ui, sans-serif';
    const prefixW = ctx.measureText(fullText.slice(0, fullText.indexOf(piiText))).width;
    const piiW = ctx.measureText(piiText).width;
    const r = canvasEl.getBoundingClientRect();
    return {
      box: { x: Math.round(r.left + 24 + prefixW), y: Math.round(r.top + ty),
             w: Math.round(piiW + 6), h: Math.round(fontSize * 1.3) },
    };
  }
  const piiBoxes = [];
  // 1) contact canvas — PII on line 2
  const c1 = document.getElementById('v-canvas');
  paintLines(c1.getContext('2d'), ['Account holder: Jane Doe (synthetic)', 'Contact: jane.doe@example.com']);
  piiBoxes.push({ type: 'email', text: 'jane.doe@example.com',
    ...measurePii(c1, 'Contact: jane.doe@example.com', 'jane.doe@example.com', 14 + 30, 20) });
  // 2) SVG data-URL image — text painted by the browser from the SVG markup
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="520" height="70">' +
    '<rect width="520" height="70" fill="#fff"/>' +
    '<text x="24" y="30" font-family="sans-serif" font-size="20" fill="#111827">Call +91 98765 43210</text></svg>';
  const img = document.getElementById('v-img');
  img.src = 'data:image/svg+xml;base64,' + btoa(svg);
  {
    const mc = document.createElement('canvas');
    mc.getContext('2d').font = '20px sans-serif';
    const r = img.getBoundingClientRect();
    const prefixW = mc.getContext('2d').measureText('Call ').width;
    const piiW = mc.getContext('2d').measureText('+91 98765 43210').width;
    piiBoxes.push({ type: 'phone', text: '+91 98765 43210',
      box: { x: Math.round(r.left + 24 + prefixW), y: Math.round(r.top + 12),
             w: Math.round(piiW + 6), h: Math.round(20 * 1.3) } });
  }
  // 3) canvas-rendered PDF-like statement — two PII lines
  const c3 = document.getElementById('v-pdf');
  paintLines(c3.getContext('2d'), ['Statement of Account — Example Bank', 'Aadhaar: 2345 1234 5909',
    'API key: sk-proj-abcdefghij1234567890', 'Page 1 of 1 — synthetic document']);
  piiBoxes.push({ type: 'aadhaar', text: '2345 1234 5909',
    ...measurePii(c3, 'Aadhaar: 2345 1234 5909', '2345 1234 5909', 14 + 30, 20) });
  piiBoxes.push({ type: 'api_key', text: 'sk-proj-abcdefghij1234567890',
    ...measurePii(c3, 'API key: sk-proj-abcdefghij1234567890', 'sk-proj-abcdefghij1234567890', 14 + 60, 20) });
  window.__SIH_GT__.ocrPiiBoxes = piiBoxes;
</script>`);

// ── write all ────────────────────────────────────────────────────────────────
// v1.14 note: GT action controls carry an explicit `via` source
// ('dom-semantic' | 'pixels-only'). The harness treats controls WITHOUT a
// `via` as 'dom-semantic' — pages that predate the source split all carry
// real DOM buttons/links.
for (const [name, html] of Object.entries(pages)) {
  writeFileSync(join(OUT, `${name}.html`), html);
  console.log(`pages/${name}.html`);
}
console.log(`\n${Object.keys(pages).length} pages written to OpenCometBench/pages/`);
